version: '3'

services:
  nginx:
    image: nginx:1.17
    working_dir: /var/www/app
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: .docker/Dockerfile-PHP
    working_dir: /var/www/app
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100M
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=dev
      - PMA_PASSWORD=dev
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:


